# **NAÏVE BAYES On a Review Classification Dataset**

# Load the Dataset

In [12]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [13]:
df = pd.read_csv("C:/Users/ksowm/Downloads/output.csv")
df.head(20)

                                               Review  Liked
0                            Wow... Loved this place.      1
1                                  Crust is not good.      0
2           Not tasty and the texture was just nasty.      0
3   Stopped by during the late May bank holiday of...      1
4   The selection on the menu was great and so wer...      1
5      Now I am getting angry and I want my damn pho.      0
6               Honeslty it didn't taste THAT fresh.)      0
7   The potatoes were like rubber and you could te...      0
8                           The fries were great too.      1
9                                      A great touch.      1
10                           Service was very prompt.      1
11                                 Would not go back.      0
12  The cashier had no care what so ever on what I...      0
13  I tried the Cape Cod ravoli, chicken, with cra...      1
14  I was disgusted because I was pretty sure that...      0
15  I was shocked because no signs indicate cash o...      0
16                                Highly recommended.      1
17             Waitress was a little slow in service.      0
18  This place is not worth your time, let alone V...      0
19                               did not like at all.      0

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0    Review  1000 non-null   object
 1   Liked    1000 non-null   int64
dtypes: int64(1), object(1)
memory usage: 15.8+ KB

In [15]:
# Space exists in columns names
df.columns = df.columns.str.strip()
df.columns

Index(['Review', 'Liked'], dtype='object')

In [16]:
df.shape

(1000, 2)

In [17]:
# Missing Values
df.isnull().sum()

Review    0
Liked     0
dtype: int64

In [18]:
# Number of samples per class
df['Liked'].value_counts()

Liked
1    500
0    500
Name: count, dtype: int64

In [19]:
df["Review"].apply(lambda x: len(x.split()))

0       4
1       4
2       8
3      15
4      12
       ..
995    12
996     3
997    10
998    16
999    28
Name: Review, Length: 1000, dtype: int64

In [20]:
df['Review'].apply(len)

0       24
1       18
2       41
3       87
4       59
      ...
995     66
996     24
997     50
998     91
999    134
Name: Review, Length: 1000, dtype: int64

In [21]:
df

                                                Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

# Train - Test Split

In [22]:
from sklearn.model_selection import train_test_split

X = df["Review"]
y = df["Liked"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Text Preprocessing (Pipeline)

In [ ]:
import re
import nltk
import joblib

from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import BernoulliNB


nltk.download("wordnet")
nltk.download("stopwords")

In [ ]:
from preprocessing import clean_text

In [31]:
model = Pipeline([
    ("tfidf", TfidfVectorizer(preprocessor=clean_text)),
    ("nb", BernoulliNB())
    ])

In [32]:
# train
model.fit(X_train,y_train)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(preprocessor=<function clean_text at 0x000001A371E5A520>)),
                ('nb', BernoulliNB())])

-  After preprocessing (df["reviews"] cleaned), we convert text → numbers.

# Evaluation

In [33]:
y_pred = model.predict(X_test)

In [34]:

from sklearn.metrics import  accuracy_score
acc = accuracy_score(y_test,y_pred)
print("Accuracy:", acc)

Accuracy: 0.75

In [35]:
# Training Accuracy 
y_train_pred = model.predict(X_train)
acc = accuracy_score(y_train,y_train_pred)
print(acc)

0.94375

In [36]:
from sklearn.metrics import precision_score, recall_score, f1_score

precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Precision: 0.75
Recall: 0.7788461538461539
F1 Score: 0.7641509433962265

In [37]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[69 27]
 [23 81]]

In [38]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.75      0.72      0.73        96
           1       0.75      0.78      0.76       104

    accuracy                           0.75       200
   macro avg       0.75      0.75      0.75       200
weighted avg       0.75      0.75      0.75       200

In [ ]:
# Save entire pipeline
import pickle

with open("sentiment_pipeline.pkl", "wb") as f:
    pickle.dump(model, f)

print("Pipeline saved again successfully")